import About from './About';
import Tieups from './Tieups';
import CollegeHistory from './CollegeHistory';
import CompanyHistory from './CompanyHistory';
import CollegeList from './CollegeList';
import Navbar from './Navbar';
import Redirection from './Redirection';
import CollegeAbout from './CollegeAbout';
import CompanyList from './CompanyList';
export { About, Tieups, CollegeList, Navbar, Redirection, CollegeAbout, CompanyList,CollegeHistory,CompanyHistory };
